name: Publish NuGet to JFrog

on:
  workflow_dispatch:   # allows manual trigger from Actions tab

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout source
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build project
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # Pack project into .nupkg
      - name: Pack NuGet package
        run: dotnet pack --configuration Release --no-build -o ./artifacts

      # Configure JFrog NuGet Source
      - name: Configure JFrog NuGet Source
        run: dotnet nuget add source "https://trial2q08ul.jfrog.io/artifactory/api/nuget/test-nuget" --name jfrog --username ${{ secrets.JFROG_USERNAME }} --password ${{ secrets.JFROG_TOKEN }} --store-password-in-clear-text

      # Push package to JFrog
      - name: Push package to JFrog
        run: dotnet nuget push ./artifacts/*.nupkg --source jfrog --skip-duplicate
